### ISSUE TITLE
How to run Dhrystone on a specific PE within TaPasCo?

### ISSUE THREAD

**Issue by AnouarNechi** [esa-tu-darmstadt/tapasco-riscv#18]
Hello

I want to run some benchmarks on the PE's available within TaPasCo beginning with Dhrystone. I had a look on the makefile but it seems only related to the hardware generation and the boards. I did not find specific instructions to run benchmarks on FPGA.
The documentation link seems broken. 
Could you point me to the documentation or the necessary steps to run Dhrystone?

Thank you

**Comment by cahz** [comment]
The first step is to create the FPGA bitstream. The Makefile in this project generates an IP core which you then can import into TaPaSCo. 

Then for running an application on the RISC-V core, you have to create a firmware (see the [example](https://github.com/esa-tu-darmstadt/tapasco-riscv/tree/master/programming/examples/PE)). A TaPaSCo host application ([example](https://github.com/esa-tu-darmstadt/tapasco-riscv/tree/master/programming/examples/host/simple_sum)) is used to load the firmware binary and execute tasks on the RISC-V.
