### ISSUE TITLE
Fix/extend clean target

### ISSUE THREAD

**Issue by tkay94** [esa-tu-darmstadt/tapasco-riscv#7]
Cores must be deleted from TAPASCO_WORK_DIR instead of TAPASCO_HOME. Git clones and other stuff is not cleaned properly as well.

**Comment by cahz** [comment]
In addition to that, the core list in the remove command should be comma separated and not space separated.

**Comment by tkay94** [comment]
Deleting multiple subdirectories in a list in curly braces like our pe list seems not to be supported in Makefiles.
